CREATE SCHEMA checklist;

CREATE TABLE checklist.tasks (
	id BIGSERIAL PRIMARY KEY,
	title varchar(255) NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	done BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)